sudo: required
language: cpp
compiler:
    - gcc
    - clang
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - wget https://github.com/g-truc/glm/archive/0.9.8.3.tar.gz
    - tar -xzvf 0.9.8.3.tar.gz
    - cd glm-0.9.8.3 && cmake . && make && sudo make install
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - cmake
            - cmake-data
            - gcc-4.8
            - g++-4.8
            - clang
            - libopencv-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make && make test

